### ISSUE TITLE
开发者须知新版

### ISSUE THREAD

**Issue by calvinyv** [QingCloudAppcenter/developer-guide#15]
青云应用中心开发者注意事项：
关于开发测试
1. 一个完整的产品不仅仅是服务创建成功就算完成任务，还要测试关闭集群、启动集群、删除集群、恢恢复集群(删除并从回收站恢复)、重启服务，横向伸缩 (如果提供此弹性能力)，纵向伸缩等操作，每次操作完毕查看 job 是否成功，确保各阶段 service 脚本的健壮性
2. 确保用户数据在每个测试之后有没有丢失。如果因为没有按照青云 AppCenter 规范开发应用导致数据丢失青云概不负责，而由应用提供商或开发者自己负责
3. 为保障应用的使用稳定性，请至少提供 health check，如提供应用监控，请确保监控告警的完备性和合理性，一般不能过多的监控指标，尽量控制在 20 个以内
4. 配置文件作为用户可见部分，开发者应站在用户角度确保配置文件的合理性，比如config.json定义死了只能一个节点，但依然提供scale_horizontal，或者数据库服务用了容量盘、默认配置过大，这都是不合理的
5. 密码不能是明文
6. 合理定义应用版本，比如多个应用其实可以合成一个多版本的应用，不然单个合作伙伴的应用会在应用中心占屏；或者有些版本确实需要分成多个应用以便管理，比如分成基础版、高级版、企业版等；

关于文字展示和说明
1. 请务必提供访问方式说明，如web管理控制台的url，用户名密码等
2. 确保应用及版本的描述及使用说明的中文及英文的正确性和合理性及易读性，有没有错别字等，应用的描述和版本的描述尽量别重复
3. 使用说明、服务条款格式要正确，比如list不能写成一排等
4. 确保提供国际化文件，如使用翻译软件辅助，请一定二次检查翻译文字的合理性
5. 如果只是单机版或体验版请在 title 注明
6. 文字描述应根据应用实际情况，避免有任何夸大，诱导性文字
7. 需要 license 的应用要在版本描述里说清楚

关于定价及收费方式
1. 定价要合情合理
2. 不清楚的地方请联系青云渠道部

**Comment by zheng1** [comment]
恢复集群 => 恢复集群(删除并从回收站恢复)

**Comment by martinyunify** [comment]
already merged into master branch

**Comment by martinyunify** [comment]
#18
